version: "3.9"
services:
  frontend:
    image: nginx
    volumes:
    #前端
      - ./templates:/etc/nginx/templates
      - ./frontend/build:/www/app/build
    ports:
      - "666:666"
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      #文件夹路径参考dockefile
      - ./public:/go/bin/public
    env_file:
      - ./backend/.env
    ports: 
      - "4567:4567"